services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - PORT=4000
      - ELASTIC_URL=http://elasticsearch:9200
    ports:
      - "4000:4000"
    depends_on:
      - elasticsearch

  seeder:
    image: node:18
    depends_on:
      - elasticsearch
      - app
    volumes:
      - ./:/app
    working_dir: /app
    command: ["sh","-c","npm install --prefix server --silent && npm run seed --prefix server"]
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
    restart: "no"

volumes:
  esdata:
